version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}